from copy import deepcopy

from blk_authority_smuggling import scan_for_authority_laundering

INDEX_ID = "blk_system_current_state_authority_index"
INDEX_STATUS = "BLK_SYSTEM_CURRENT_STATE_AUTHORITY_INDEX"
READY = "CURRENT_STATE_INDEX_READY_FOR_OPERATOR_REVIEW_NOT_AUTHORITY"
BLOCKED = "CURRENT_STATE_INDEX_BLOCKED"
MATURITY = "CURRENT_STATE_INDEX_L0_L1_ONLY"

NEXT_FRONTIER_321 = (
    "NEXT_FRONTIER_BLK_SYSTEM_9_OF_10_REPO_DEVELOPMENT_READY_"
    "SIDE_EFFECT_APPROVALS_SEPARATE_NOT_GRANTED"
)
NEXT_FRONTIER_322 = "NEXT_FRONTIER_9_9_FIRST_PASS_OPERATOR_REVIEW_AND_VERIFICATION_GAPS_NOT_10_OF_10"
NEXT_FRONTIER_325 = "NEXT_FRONTIER_9_OF_10_OVERALL_SIDE_EFFECT_DECISION_REQUIRED_NOT_GRANTED"
EXPECTED_325_OVERALL_GUARD_HASH = (
    "sha256:18f9550996bc0388e67666237c0e95d81906ce30162c184401149eeffb31dd3e"
)
EXPECTED_317_FRONTIER_HASH = (
    "sha256:99df97cf8a7e553ecb9a28d6a814103977caa52b3e6df1a1df3c1f6342134af8"
)
EXPECTED_318_REQUEST_HASH = (
    "sha256:4425cad711a5f77d389aa4ccca9e6d0606797431d1af8031103774c183605197"
)
EXPECTED_319_GUARD_HASH = (
    "sha256:fe8e9f00a09a717ba23eb998411a2b626f94029a218d789a4ad07c6f57dff4c3"
)
EXPECTED_320_READINESS_MATRIX_HASH = (
    "sha256:c1f7538331042a94d6b1e8c964688a24a91b1ea64bcbbd55f814d4e03feee860"
)
EXPECTED_321_RECONCILIATION_HASH = (
    "sha256:7237998c0d31ba47ff4972c2177cdb545bb69fed87f3c64f403ade63b9be6d64"
)

DENIED_FLAGS = (
    "runtime_authority_granted",
    "live_codex_execution_authorized",
    "blk_pipe_dispatch_authorized",
    "production_blk_test_mcp_authorized",
    "beb_dispatch_authorized",
    "beo_closeout_execution_authorized",
    "authoritative_beo_publication_authorized",
    "reusable_beo_publication_authorized",
    "beo_publication_signer_reuse_authorized",
    "beo_publication_storage_reuse_authorized",
    "beo_publication_ledger_reuse_authorized",
    "rollback_revocation_supersession_authorized",
    "runtime_rtm_generation_authorized",
    "reusable_rtm_generation_authorized",
    "production_blk_link_authorized",
    "rtm_drift_rejection_authorized",
    "rtm_coverage_truth_authorized",
    "active_vault_comparison_authorized",
    "protected_blk_req_body_reads_authorized",
    "protected_blk_req_body_copy_authorized",
    "protected_blk_req_body_parse_authorized",
    "protected_blk_req_body_hash_authorized",
    "protected_blk_req_body_scan_authorized",
    "target_source_git_mutation_authorized",
    "network_model_cyber_browser_tooling_authorized",
    "package_manager_authorized",
    "production_isolation_claimed",
)

DOC_DENIAL_MARKERS = {
    "runtime_authority_granted": ("no runtime tooling", "no BLK-pipe runtime"),
    "live_codex_execution_authorized": ("no live Codex",),
    "blk_pipe_dispatch_authorized": ("no BLK-pipe runtime",),
    "production_blk_test_mcp_authorized": ("no production BLK-test MCP", "production/generic BLK-test MCP"),
    "beb_dispatch_authorized": ("no BEB dispatch",),
    "beo_closeout_execution_authorized": ("no BEO closeout execution",),
    "authoritative_beo_publication_authorized": ("no reusable BEO publication", "no future publication run"),
    "reusable_beo_publication_authorized": ("no reusable BEO publication",),
    "beo_publication_signer_reuse_authorized": ("no signer reuse", "no reusable BEO publication/signing"),
    "beo_publication_storage_reuse_authorized": ("no storage reuse", "no reusable BEO publication/signing/storage"),
    "beo_publication_ledger_reuse_authorized": ("no ledger reuse", "no reusable BEO publication/signing/storage/ledger"),
    "rollback_revocation_supersession_authorized": ("no rollback/revocation/supersession", "rollback, revocation, or supersession execution"),
    "runtime_rtm_generation_authorized": ("no reusable RTM generation", "further RTM generation"),
    "reusable_rtm_generation_authorized": ("no reusable RTM generation",),
    "production_blk_link_authorized": ("no production `blk-link`",),
    "rtm_drift_rejection_authorized": ("no drift rejection",),
    "rtm_coverage_truth_authorized": ("no coverage truth",),
    "active_vault_comparison_authorized": ("no active-vault comparison", "no new active-vault comparison"),
    "protected_blk_req_body_reads_authorized": ("no protected-body access", "no protected BLK-req body reads"),
    "protected_blk_req_body_copy_authorized": ("copying", "reads/copying/parsing"),
    "protected_blk_req_body_parse_authorized": ("parsing", "reads/copying/parsing"),
    "protected_blk_req_body_hash_authorized": ("hashing", "parsing/hashing/scanning"),
    "protected_blk_req_body_scan_authorized": ("scanning", "hashing/scanning/mutation"),
    "target_source_git_mutation_authorized": ("no target/source/Git mutation", "no source/Git mutation"),
    "network_model_cyber_browser_tooling_authorized": ("no package/network/model/browser/cyber tooling",),
    "package_manager_authorized": ("no package/network/model/browser/cyber tooling", "package-manager"),
    "production_isolation_claimed": ("no production-isolation claim", "production-isolation claims"),
}

ACTIVE_DOC_REQUIRED_MARKERS = (
    "BLK_SYSTEM_325_OVERALL_9_DIRECTIVE_GUARDED",
    NEXT_FRONTIER_325,
    EXPECTED_325_OVERALL_GUARD_HASH,
    "BLK_SYSTEM_323_BEB_L2_ROUTE_ARTIFACT_BOUNDARY_HARDENED",
    "BLK_SYSTEM_322_ROOT_DOCTRINE_ROADMAP_FIRST_PASS_DONE_FOR_9_9_REVIEW_READY",
    NEXT_FRONTIER_322,
    "BLK_SYSTEM_321_9_OF_10_DEVELOPMENT_UNBLOCK_RECONCILED",
    NEXT_FRONTIER_321,
    "BLK_SYSTEM_320_9_OF_10_READINESS_MATRIX_READY",
    "BLK_SYSTEM_319_DEVELOPMENT_DIRECTIVE_GUARD_RECORDED",
    "BLK_SYSTEM_318_EXACT_NO_CLOCK_SIDE_EFFECT_REQUEST_READY",
    "BLK_SYSTEM_317_9_OF_10_DEVELOPMENT_FRONTIER_BOUND",
    "BLK_SYSTEM_316_STANDING_BLK_SYSTEM_DEVELOPMENT_APPROVAL_RECORDED",
    "BLK_SYSTEM_315_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_LIVE_REFRESH_NON_APPROVAL_RECONCILED",
    "BLK_SYSTEM_314_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_SHORT_APPROVE_GUARD_READY",
    "BLK_SYSTEM_313_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_LIVE_REFRESH_GENERIC_DIRECTIVE_RECORDED",
    "BLK_SYSTEM_312_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_REFRESH_CHALLENGE_RECONCILED",
    "BLK_SYSTEM_311_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_REFRESH_APPROVE_CHALLENGE_READY",
    "BLK_SYSTEM_310_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_CHALLENGE_EXPIRED_ATTEMPT_RECORDED",
    "BLK_SYSTEM_309_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_REQUEST_RECONCILED",
    "BLK_SYSTEM_308_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_CHALLENGE_RECORDED",
    "BLK_SYSTEM_307_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_REQUEST_CONTRACT_READY",
    "BLK_SYSTEM_306_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_REQUEST_READY",
    "NEXT_FRONTIER_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_CAPTURE_AND_BOUNDED_EXECUTION_REQUIRED_NOT_GRANTED",
    "BLK_SYSTEM_305_VERIFIED_LOOP_BEO_PUBLICATION_REVIEW_RECONCILED",
    "BLK_SYSTEM_304_VERIFIED_LOOP_BEO_PUBLICATION_REVIEW_RECORDED",
    "BLK_SYSTEM_303_VERIFIED_LOOP_BEO_PUBLICATION_REVIEW_CONTRACT_READY",
    "BLK_SYSTEM_302_VERIFIED_LOOP_BEO_PUBLICATION_REVIEW_REQUEST_READY",
    "NEXT_FRONTIER_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_REQUEST_REQUIRED_NOT_GRANTED",
    "NEXT_FRONTIER_VERIFIED_LOOP_BEO_PUBLICATION_REVIEW_REQUIRED_NOT_GRANTED",
    "BLK_SYSTEM_301_EXACT_BLK_TEST_ORACLE_VERIFICATION_RECONCILED",
    "BLK_SYSTEM_300_EXACT_BLK_TEST_ORACLE_VERIFICATION_RECORDED",
    "BLK_SYSTEM_299_EXACT_BLK_TEST_ORACLE_VERIFICATION_PREFLIGHT_READY",
    "BLK_SYSTEM_298_EXACT_BLK_TEST_ORACLE_VERIFICATION_CONTRACT_READY",
    "NEXT_FRONTIER_EXACT_BLK_TEST_ORACLE_VERIFICATION_AFTER_LOOP_EXECUTION_REQUIRED_NOT_GRANTED",
    "BLK_SYSTEM_297_EXACT_QUARANTINE_GATED_BLK003_LOOP_EXECUTION_RECONCILED",
    "BLK_SYSTEM_296_QUARANTINE_BOUNDED_BLK003_LOOP_EXECUTION_RECORDED",
    "BLK_SYSTEM_295_FRESH_TARGET_WORKTREE_SANDBOX_PREFLIGHT_READY",
    "BLK_SYSTEM_294_EXACT_QUARANTINE_GATED_BLK003_LOOP_EXECUTION_PACKAGE_READY",
    "BLK_SYSTEM_293_REUSABLE_BLK003_LOOP_REQUEST_PATH_RECONCILED",
    "BLK_SYSTEM_292_QUARANTINE_GATED_REQUEST_PREFLIGHT_READY",
    "BLK_SYSTEM_291_BEB_L2_ROUTE_REQUEST_BINDING_READY",
    "BLK_SYSTEM_290_BLK003_LOOP_REQUEST_CONTRACT_READY",
    "NEXT_FRONTIER_EXACT_QUARANTINE_GATED_BLK003_LOOP_EXECUTION_PACKAGE_REQUIRED_NOT_GRANTED",
    "BLK_SYSTEM_289_PROMOTION_PURGE_STALE_GATE_READY",
    "BLK_SYSTEM_288_SPECULATIVE_QUARANTINE_EVIDENCE_READY",
    "BLK_SYSTEM_287_HITL_INTERACTION_IDENTITY_RELAY_EVIDENCE_READY",
    "BLK_SYSTEM_286_SPECULATIVE_QUARANTINE_APPROVAL_CONTRACT_READY",
    "NEXT_FRONTIER_REUSABLE_BLK003_LOOP_REQUEST_PATH_WITH_QUARANTINE_GATE_NOT_GRANTED",
    "BLK_SYSTEM_285_IDENTITY_RELAY_LOOP_EVIDENCE_READY",
    "BLK_SYSTEM_284_BLK_RELAY_ENVELOPE_CONTRACT_READY",
    "BLK_SYSTEM_283_BLK_IDENTITY_SPINE_CONTRACT_READY",
    "NEXT_FRONTIER_HITL_GATEWAY_IDENTITY_RELAY_WIRING_NOT_GRANTED",
    "BLK_SYSTEM_282_AGENT_A_REQUIREMENT_CONTEXT_SUMMARY_FEATURE_DROP_EXECUTED",
    "BLK_SYSTEM_281_RTM_BLK_LINK_DRIFT_COVERAGE_SECOND_REFRESH_CHALLENGE_RECONCILED",
    "BLK_SYSTEM_280_RTM_BLK_LINK_DRIFT_COVERAGE_SECOND_REFRESH_APPROVE_CHALLENGE_READY",
    "BLK_SYSTEM_279_RTM_BLK_LINK_DRIFT_COVERAGE_REFRESHED_CHALLENGE_EXPIRED_ATTEMPT_RECORDED",
    "NEXT_FRONTIER_RTM_BLK_LINK_DRIFT_COVERAGE_SECOND_REFRESHED_BOUND_APPROVE_REQUIRED_NOT_GRANTED",
    "BLK_SYSTEM_278_RTM_BLK_LINK_DRIFT_COVERAGE_REFRESH_CHALLENGE_RECONCILED",
    "BLK_SYSTEM_277_RTM_BLK_LINK_DRIFT_COVERAGE_REFRESH_APPROVE_CHALLENGE_READY",
    "BLK_SYSTEM_276_RTM_BLK_LINK_DRIFT_COVERAGE_EXPIRED_APPROVE_ATTEMPT_RECORDED",
    "NEXT_FRONTIER_RTM_BLK_LINK_DRIFT_COVERAGE_REFRESHED_BOUND_APPROVE_REQUIRED_NOT_GRANTED",
    "BLK_SYSTEM_275_RTM_BLK_LINK_DRIFT_COVERAGE_REQUEST_RECONCILED",
    "BLK_SYSTEM_274_RTM_BLK_LINK_DRIFT_COVERAGE_APPROVAL_PREFLIGHT_BLOCKED",
    "BLK_SYSTEM_273_RTM_BLK_LINK_DRIFT_COVERAGE_APPROVE_CHALLENGE_READY",
    "BLK_SYSTEM_272_RTM_BLK_LINK_DRIFT_COVERAGE_REQUEST_READY",
    "NEXT_FRONTIER_RTM_BLK_LINK_DRIFT_COVERAGE_BOUND_APPROVE_OR_EXACT_TEXT_REQUIRED_NOT_GRANTED",
    "BLK_SYSTEM_271_EXACT_BEO_PUBLICATION_FINALITY_RECONCILED",
    "BLK_SYSTEM_270_EXACT_BEO_PUBLICATION_FINALITY_RECORD_EXECUTED",
    "BLK_SYSTEM_269_EXACT_BEO_PUBLICATION_EXECUTION_APPROVAL_CAPTURED",
    "NEXT_FRONTIER_RTM_BLK_LINK_DRIFT_COVERAGE_REQUEST_READY_AFTER_EXACT_BEO_PUBLICATION",
    "BLK_SYSTEM_268_EXACT_BEO_PUBLICATION_RUN_PACKAGE_RECONCILED",
    "BLK_SYSTEM_267_EXACT_BEO_PUBLICATION_RUN_PREFLIGHT_BLOCKED",
    "BLK_SYSTEM_266_EXACT_BEO_PUBLICATION_RUN_PACKAGE_READY",
    "NEXT_FRONTIER_EXACT_BEO_PUBLICATION_EXECUTION_APPROVAL_REQUIRED_NOT_GRANTED",
    "BLK_SYSTEM_265_EXACT_BEO_PUBLICATION_APPROVAL_CAPTURE_RECONCILED",
    "BLK_SYSTEM_264_EXACT_BEO_PUBLICATION_OPERATOR_APPROVAL_CAPTURED",
    "NEXT_FRONTIER_EXACT_BEO_PUBLICATION_RUN_PACKAGE_REQUIRED_NOT_EXECUTED",
    "BLK_SYSTEM_263_SPRINT_PACKAGE_SELECTION_GATE_READY",
    "BLK_SYSTEM_262_SPRINT_PACKAGE_GRANULARITY_CONTRACT_READY",
    "BLK_SYSTEM_261_SPRINT_PACKAGE_FRONTIER_REVIEW_READY",
    "BLK_SYSTEM_260_EXACT_BEO_PUBLICATION_APPROVAL_RECONCILED_NOT_GRANTED",
    "BLK_SYSTEM_259_EXACT_BEO_PUBLICATION_APPROVAL_PREFLIGHT_RECORDED",
    "BLK_SYSTEM_258_EXACT_BEO_PUBLICATION_OPERATOR_APPROVAL_CONTRACT_READY",
    "BLK_SYSTEM_257_EXACT_BEO_PUBLICATION_RUN_REQUEST_READY",
    "NEXT_FRONTIER_EXACT_BEO_PUBLICATION_OPERATOR_APPROVAL_TEXT_REQUIRED_NOT_GRANTED",
    "BLK_SYSTEM_256_RTM_BLK_LINK_DRIFT_COVERAGE_RECONCILED",
    "BLK_SYSTEM_255_EXACT_METADATA_ONLY_DRIFT_COVERAGE_DRY_RUN_RECORDED",
    "BLK_SYSTEM_254_DRIFT_COVERAGE_VERIFIER_CONTRACT_READY",
    "BLK_SYSTEM_253_RTM_BLK_LINK_DRIFT_COVERAGE_REQUEST_SCOPED",
    "BLK_SYSTEM_252_RTM_BLK_LINK_DRIFT_COVERAGE_SURFACE_REVIEW_READY",
    "NEXT_FRONTIER_EXACT_BEO_PUBLICATION_RUN_REQUIRED_FOR_RTM_DRIFT_COVERAGE_NOT_GRANTED",
    "BLK_SYSTEM_251_REUSABLE_BEO_PUBLICATION_RECONCILED_PER_RUN_EXACT_APPROVAL_READY",
    "BLK_SYSTEM_250_BLK003_LOOP_BEO_PUBLICATION_REVIEW_INTEGRATION_READY",
    "BLK_SYSTEM_249_EXACT_BEO_PUBLICATION_DRY_RUN_REVIEW_READY",
    "BLK_SYSTEM_248_REUSABLE_BEO_PUBLICATION_CONTRACT_READY",
    "BLK_SYSTEM_247_REUSABLE_BEO_PUBLICATION_REQUEST_SCOPED",
    "BLK_SYSTEM_246_PRODUCTION_BLK_TEST_MCP_ORACLE_RECONCILED_VERIFIER_ONLY",
    "BLK_SYSTEM_245_BLK003_LOOP_ORACLE_EVIDENCE_INTEGRATION_READY",
    "BLK_SYSTEM_244_METADATA_ONLY_BLK_TEST_ORACLE_FIXTURE_READY",
    "BLK_SYSTEM_243_PRODUCTION_BLK_TEST_MCP_ORACLE_CONTRACT_READY",
    "BLK_SYSTEM_242_PRODUCTION_BLK_TEST_MCP_ORACLE_REQUEST_SCOPED",
    "BLK_SYSTEM_241_REUSABLE_BLK003_LOOP_KERNEL_READY",
    "BLK_SYSTEM_240_HITL_GATEWAY_COMPLETION_SLICE_READY",
    "BLK_SYSTEM_239_BLK_ID_RELAY_SCOPE_DECIDED",
    "BLK_SYSTEM_238_ROOT_DOCTRINE_DEVIATION_OVERLAY_READY",
    "BLK_SYSTEM_237_KURONODE_ROUTE_SELECTION_READY",
    "BLK_SYSTEM_235_AGENT_A_CONTEXT_PACKET_PR_MERGED",
    "BLK_SYSTEM_234_REPEAT_KURONODE_FEATURE_DROP_EXECUTED",
    "BLK_SYSTEM_233_CODEX_PROGRESS_EVENTS_READY",
    "BLK_SYSTEM_232_BEB_L2_PACKET_HELPER_READY",
    "BLK_SYSTEM_231_AGENT_A_HEADER_PR_MERGED",
    "BLK_SYSTEM_230_AGENT_A_HEADER_DROP_EXECUTED",
    "BLK_SYSTEM_229_PRIVATE_BWRAP_WORKSPACE_WRITE_SETUP_READY",
    "BLK_SYSTEM_228_EXACT_KURONODE_CLEAN_WORKTREE_FEATURE_DROP_EXECUTED",
    "BLK_SYSTEM_227_EXTERNAL_CODEX_ARTIFACT_READY",
    "BLK_SYSTEM_226_KURONODE_WORKTREE_STATIC_PROFILE_READY",
    "BLK_SYSTEM_225_CLEAN_WORKTREE_MANIFEST_READY",
    "BLK_SYSTEM_224_IGNORED_RESIDUE_CLEANUP_PLAN_READY",
    "BLK_SYSTEM_223_BEB_L2_PREFLIGHT_GUARD_READY",
    "BLK_SYSTEM_222_BEB_L2_BLK_PIPE_CODEX_ROUTE_READY",
    "BLK_SYSTEM_221_FOURTH_BOUNDED_KURONODE_FEATURE_LOOP_EXECUTED",
    "BLK_SYSTEM_220_NATIVE_CODEX_SANDBOX_REPAIR_RECHECK_RECORDED",
    "BLK_SYSTEM_219_NATIVE_CODEX_SANDBOX_MITIGATION_RECORDED",
    "BLK_SYSTEM_218_THIRD_BOUNDED_KURONODE_FEATURE_LOOP_EXECUTED",
    "BLK_SYSTEM_217_CODEX_EXACT_UNDO_EXERCISE_RECORDED",
    "BLK_SYSTEM_216_CODEX_PERMISSION_PROFILE_CONTAINMENT_DRILL_RECORDED",
    "BLK_SYSTEM_215_SUPERVISED_CODEX_KURONODE_FEATURE_LOOP_EXECUTED",
    "BLK_SYSTEM_214_BOUNDED_KURONODE_FEATURE_LOOP_EXECUTED",
    "BLK_SYSTEM_213_BLK_TEST_OPTIONAL_DIAGNOSTIC_UNBLOCK_READY",
    "BLK_SYSTEM_212_VALIDATION_PROFILE_RECONCILED_CLEAN",
    "BLK_SYSTEM_211_VALIDATION_PROFILE_CONTRACT_READY",
    "BLK_SYSTEM_210_VALIDATION_PROFILE_SURFACE_REVIEW_READY",
    "BLK_SYSTEM_209_PYTHON_ADAPTER_RECONCILED_CLEAN",
    "BLK_SYSTEM_208_PYTHON_ADAPTER_CONTRACT_READY",
    "BLK_SYSTEM_207_PYTHON_ADAPTER_SURFACE_REVIEW_READY",
    "BLK_SYSTEM_206_BLK_PIPE_BOUNDED_ENFORCEMENT_RECONCILED_CLEAN",
    "BLK_SYSTEM_205_BLK_PIPE_BOUNDED_ENFORCEMENT_CONTRACT_READY",
    "BLK_SYSTEM_204_BLK_PIPE_SURFACE_REVIEW_READY",
    "BLK_SYSTEM_203_KURONODE_BLK_REQ_BRIDGE_RECONCILED_CLEAN",
    "BLK_SYSTEM_202_KURONODE_BLK_REQ_EXACT_ID_MAPPING_MATERIALIZED",
    "BLK_SYSTEM_201_KURONODE_BLK_REQ_EXACT_ID_MAPPING_MANIFEST_READY",
    "BLK_SYSTEM_200_KURONODE_BLK_REQ_VAULT_BOOTSTRAP_BLUEPRINT_READY",
    "BLK_SYSTEM_199_BLK_REQ_PRODUCTION_GATEWAY_RECONCILED_CLEAN",
    "BLK_SYSTEM_198_BLK_REQ_GATEWAY_HOSTILE_INPUTS_HARDENED",
    "BLK_SYSTEM_197_BLK_REQ_EXACT_ID_LIFECYCLE_SMOKE_PASSED",
    "BLK_SYSTEM_196_BLK_REQ_PRODUCTION_GATEWAY_CONTRACT_READY",
    "BLK_SYSTEM_195_BLK_REQ_GATEWAY_READINESS_REVIEW_CLEAN",
    "BLK_SYSTEM_194_REPEATABLE_TRUSTED_BLK_LINK_RECONCILED_CLEAN",
    "BLK_SYSTEM_193_REPEATABLE_TRUSTED_BLK_LINK_REPEAT_RUNS_RECORDED_CLEAN",
    "BLK_SYSTEM_192_REPEATABLE_TRUSTED_BLK_LINK_LEDGER_READY",
    "BLK_SYSTEM_191_REPEATABLE_TRUSTED_BLK_LINK_CONTRACT_EMITTED",
    "BLK_SYSTEM_190_REPEATABLE_TRUSTED_BLK_LINK_POST_RUN_REVIEW_CLEAN",
    "BLK_SYSTEM_189_SINGLE_PRODUCTION_BLK_LINK_WRAPPER_RUN_RECONCILED_CLEAN",
    "BLK_SYSTEM_188_SINGLE_PRODUCTION_BLK_LINK_WRAPPER_RUN_EXECUTION_RECORDED",
    "BLK_SYSTEM_187_SINGLE_PRODUCTION_BLK_LINK_WRAPPER_RUN_REQUEST_READY",
    "BLK_SYSTEM_186_REUSABLE_BLK_LINK_READINESS_KERNEL_RECONCILED_CLEAN",
    "BLK_SYSTEM_182_RTM_BLK_LINK_PROTECTED_BODY_EVIDENCE_EXPORT_RECONCILED_CLEAN",
    "BLK_SYSTEM_181_RTM_BLK_LINK_PROTECTED_BODY_EVIDENCE_METADATA_EXPORT_EMITTED",
    "BLK_SYSTEM_180_RTM_BLK_LINK_PROTECTED_BODY_EVIDENCE_FOLLOWUP_RECONCILED_CLEAN",
    "BLK_SYSTEM_179_RTM_BLK_LINK_PROTECTED_BODY_EVIDENCE_FOLLOWUP_EXECUTION_RECORDED",
    "BLK_SYSTEM_178_RTM_BLK_LINK_PROTECTED_BODY_EVIDENCE_FOLLOWUP_AUTHORITY_REQUEST_READY",
    "BLK_SYSTEM_177_AUTHORITY_LAUNDERING_BYPASS_HARDENED",
    "BLK_SYSTEM_176_RTM_BLK_LINK_PROTECTED_BODY_VERIFICATION_EVIDENCE_INTEGRATED",
    "BLK_SYSTEM_175_PROTECTED_BODY_VERIFICATION_DECISION_EXECUTION_RECORDED",
    "BLK_SYSTEM_174_PROTECTED_BODY_VERIFICATION_DECISION_AUTHORITY_REQUEST_READY",
    "BLK_SYSTEM_173_METADATA_BOUND_DRIFT_COVERAGE_DECISION_RECONCILED_CLEAN",
    "BLK_SYSTEM_172_METADATA_BOUND_DRIFT_COVERAGE_DECISION_EXECUTION_RECORDED",
    "BLK_SYSTEM_171_METADATA_BOUND_DRIFT_COVERAGE_DECISION_AUTHORITY_REQUEST_READY",
    "BLK_SYSTEM_170_ACTIVE_VAULT_HASH_COMPARISON_RECONCILED_CLEAN",
    "BLK_SYSTEM_169_ACTIVE_VAULT_HASH_COMPARISON_DECISION_EXECUTION_RECORDED",
    "BLK_SYSTEM_168_ACTIVE_VAULT_HASH_COMPARISON_AUTHORITY_REQUEST_READY",
    "BLK_SYSTEM_167_PRODUCTION_BLK_LINK_RTM_TRACE_CLOSURE_POST_RUN_RECONCILED_CLEAN",
    "BLK_SYSTEM_166_PRODUCTION_BLK_LINK_RTM_TRACE_CLOSURE_DECISION_EXECUTION_RECORDED",
    "BLK_SYSTEM_165_PRODUCTION_BLK_LINK_RTM_TRACE_CLOSURE_AUTHORITY_REQUEST_READY",
    "BLK_SYSTEM_164_ACTIVE_DOC_DENIED_SURFACE_SYNC_HARDENED",
    "BLK_SYSTEM_163_CURRENT_STATE_DENIED_SURFACE_HARDENED",
    "blk204_surface_review_package_hash=sha256:324a218f4a6681883e6cb82d097239730386b3e290f9ed112c651eb2a7cde8d9",
    "blk205_enforcement_contract_hash=sha256:108d03e3e3f4cbb57a8fbd58691bb3e24d4cda7aad957e8ac5842d0ae52ba9d4",
    "blk206_reconciliation_package_hash=sha256:666db65980b1767f84e919491dcc54096b260d4cc91972f7b9f67281a9706fba",
    "blk207_adapter_review_package_hash=sha256:5fd1aa5428a13349a62da76bf66e5ddaeef510ab7582a12ff1f1a45cad6a2298",
    "blk208_adapter_contract_package_hash=sha256:d98159f614cb2e9c248df151efec7489eab306eeceb2d9d4a7f94b21acabdb9c",
    "blk209_adapter_reconciliation_package_hash=sha256:02a9084ec1aab3e589da5c8a7417e371d78e3e1e706b27f51fde9ab1b5b79a61",
    "blk210_profile_review_package_hash=sha256:0c754f86a9335c11610b74bb0d6f6808f9c0d9ce7afa2ab36eab7d591ffdfe32",
    "blk211_profile_contract_package_hash=sha256:b1aed5f05923afee76206c0f1b406034cb5da0b9c743686e0faa493806a6baa7",
    "blk212_profile_reconciliation_package_hash=sha256:77fa8dcc7d28b1084443169d43bff3f87e2fee85d082d0c8281e9e5807a4f905",
    "blk213_blk_test_unblock_package_hash=sha256:0cae4030ca2ff06792f80762259fcd3ab00731bf00f4ee4f4ba158f4654a0381",
    "blk214_feature_loop_package_hash=sha256:87f15b82ec5f78450e49638544d406845180ca1bdd7915be7323ae98677172e8",
    "blk215_supervised_codex_feature_loop_package_hash=sha256:4e2d6bd3c7d7d452452fa5a018a8e649e7cf614a9d33158b2232ee40c68f83a4",
    "blk216_codex_config_containment_package_hash=sha256:3e1cf8a9dcbb6dc8826d203d65b26ed01649ad1de0b6a3eda7e8d7741ec7434e",
    "blk217_codex_exact_undo_package_hash=sha256:b730e69e4126377c4f726e3bfd9648e3c6478ac6bd21aa9ddc26d221ffa7c506",
    "blk218_selected_requirement_badge_feature_hash=sha256:b5310ed5bd41c6717c733f8cfbb98de7fd03b0f37d602990e6a100b9a255f1d3",
    "blk219_native_codex_sandbox_mitigation_hash=sha256:710dd82eabda1f2d792dfc8cce2af88612603ea0b1683e5ad644bc1453312404",
    "blk220_native_codex_sandbox_repair_recheck_hash=sha256:9d63c4b7d99615db812e3751718574ce96cf101fc755af6d50ccc50d7f10146e",
    "blk221_loading_state_feature_hash=sha256:232a1f494d4edea48438273382091f3ecc61e600545026bd29f63b22f20dc8f3",
    "blk222_beb_l2_blk_pipe_codex_route_hash=sha256:52b85fd75fb2542ed9aa05ec790986bbf40e21ea178d5c6c6f07a245e10b55fa",
    "blk223_beb_l2_preflight_guard_hash=sha256:c1ee4c9bdcf76c0e315095f4f858f3e33b5d6eaee55cf3f8651d1dc3768edf84",
    "blk224_ignored_residue_cleanup_plan_hash=sha256:e2e826e979ac42106eb1c05d885bd12e471e3cc6a9042f177cc4a404c5eb90d9",
    "blk225_clean_worktree_manifest_hash=sha256:f13e65c959415edb4b44f52577ae0f94862f04bdec54347addad49c40f3e9a43",
    "blk226_kuronode_worktree_static_profile_hash=sha256:e287c7e84668b9e7a1667671c5561ee7da39bc4c614694182677b98b770805fc",
    "blk227_external_codex_artifact_hash=sha256:848df7dd040d145e955517616225c60fc24ddbea60ea982fa0599ecd2aba094c",
    "blk228_clean_worktree_feature_drop_hash=sha256:93541bf31fd0a227d94b8a34c9bccb8a95cf406a12ae98cbd8b3fb7a7038ef12",
    "blk229_private_bwrap_workspace_write_setup_hash=sha256:1cadd6e9f379bb814f86a50e22cd1e351b8961bbfb7e3c6778ca771075d5722f",
    "blk230_agent_a_header_feature_drop_hash=sha256:82c8cbfa501a1f113a5262e71f6b210c42b017884e4754b073b02f55af4ba6d1",
    "blk231_agent_a_header_pr_merge_hash=sha256:71bf9890d647a1faf8b853b0f9178cf88f24fdc09d6b82f8d6d2d4a5f55806be",
    "blk232_beb_l2_packet_helper_hash=sha256:ec15a886c7b88a6c06260ec9125f2cc4285b435044f24aafbc3235bc0da16bf7",
    "blk233_codex_progress_events_hash=sha256:7d7f65ec2003454431cc65cc551d722a8e3263c39688932b673b6e0bbc06826d",
    "blk234_repeat_feature_drop_hash=sha256:25b4e234301cf2255e2591a6dd1e6858d7c025411666e432c2ba12d82297c9b9",
    "blk283_identity_contract_hash=sha256:b7bdbb14890a4ebadcf2e286ca7cf78a899b02cf55cf336bc0681d095662c251",
    "blk284_relay_contract_hash=sha256:d209df42c15863a373c7338bd249d24d5f6ae1cba1f1ddd873d2ef8acfdf54ca",
    "blk285_identity_relay_loop_evidence_hash=sha256:574b9bfcc919331a28b7919c5412362440f8447a3a0df4d2ad27dc751e16a373",
    "blk282_agent_a_requirement_context_summary_drop_hash=sha256:cd2b3ed9392bcff7fc448ac8573373dbc823b218cbd0d9e3550c87672cc1b376",
    "blk235_agent_a_context_packet_pr_merge_hash=sha256:27aad98cf1356ccd1b5c401996664adad5d0f9a372c3af2d2db6e8f4214b639f",
)

STALE_ACTIVE_DOC_MARKERS = (
    "NEXT_FRONTIER_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_REFRESHED_BOUND_APPROVE_REQUIRED_NOT_GRANTED",
    "NEXT_FRONTIER_NEXT_EXACT_KURONODE_FEATURE_OR_OBSERVED_WORKTREE_HARDENING_NOT_BLANKET_AUTHORITY",
    "NEXT_FRONTIER_OPERATOR_DECIDE_KURONODE_RESIDUE_CLEAN_OR_SPLIT_NOT_MUTATION_AUTHORITY",
    "NEXT_FRONTIER_EXACT_KURONODE_FEATURE_DROP_AFTER_PREFLIGHT_NOT_BLANKET_AUTHORITY",
    "NEXT_FRONTIER_OPERATOR_SELECTED_NEXT_BOUNDED_KURONODE_FEATURE_OR_OBSERVED_FAILURE_HARDENING_NOT_GRANTED",
    "NEXT_FRONTIER_OPERATOR_SELECTED_BOUNDED_KURONODE_FEATURE_WITH_NATIVE_WORKSPACE_WRITE_RECHECK_OR_EXTERNAL_CONTAINMENT_NOT_GRANTED",
    "NEXT_FRONTIER_OPERATOR_SELECTED_BOUNDED_KURONODE_FEATURE_WITH_EXTERNAL_CONTAINMENT_OR_HOST_ADMIN_SANDBOX_REPAIR_NOT_GRANTED",
    "NEXT_FRONTIER_OPERATOR_SELECTED_BOUNDED_KURONODE_FEATURE_OR_OBSERVED_FAILURE_HARDENING_NOT_GRANTED",
    "NEXT_FRONTIER_THIRD_BOUNDED_KURONODE_FEATURE_LOOP_AVAILABLE_AFTER_UNDO_CHECK_NOT_GRANTED",
    "NEXT_FRONTIER_THIRD_BOUNDED_KURONODE_FEATURE_LOOP_OR_EXACT_UNDO_WITH_CODEX_PROFILE_CONTAINMENT_AVAILABLE_NOT_GRANTED",
    "NEXT_FRONTIER_THIRD_BOUNDED_KURONODE_FEATURE_LOOP_OR_OPERATOR_SELECTED_UNDO_NOT_GRANTED",
    "NEXT_FRONTIER_SECOND_BOUNDED_KURONODE_FEATURE_LOOP_OR_OPERATOR_SELECTED_UNDO_NOT_GRANTED",
    "NEXT_FRONTIER_VALIDATION_PROFILES_CLOSED_BLK_TEST_SELECTION_NOT_GRANTED",
    "NEXT_FRONTIER_PYTHON_ADAPTER_CLOSED_VALIDATION_PROFILES_SELECTION_NOT_GRANTED",
    "NEXT_FRONTIER_BLK_PIPE_CLOSED_NEXT_COMPONENT_SELECTION_NOT_GRANTED",
    "NEXT_FRONTIER_OPERATOR_SELECTED_BOUNDED_CAPABILITY_AFTER_CLEAN_RECONCILIATION_NOT_GRANTED",
    "NEXT_FRONTIER_PRODUCTION_BLK_LINK_RTM_TRACE_CLOSURE_APPROVAL_CAPTURE_NOT_GRANTED",
    "NEXT_FRONTIER_HARDENING_ONLY_COMPLETE_AUTHORITY_NOT_GRANTED",
    "NEXT_FRONTIER_FURTHER_HARDENING_OR_AUTHORITY_REQUEST_NOT_GRANTED",
    "NEXT_FRONTIER_METADATA_BOUND_DRIFT_COVERAGE_DECISION_APPROVAL_NOT_GRANTED",
    "NEXT_FRONTIER_PROTECTED_BODY_VERIFICATION_DECISION_APPROVAL_NOT_GRANTED",
    "NEXT_FRONTIER_RTM_BLK_LINK_PROTECTED_BODY_VERIFICATION_EVIDENCE_READY_NOT_REUSABLE_AUTHORITY",
    "NEXT_FRONTIER_DOWNSTREAM_METADATA_EXPORT_REQUEST_NOT_GRANTED",
    "NEXT_FRONTIER_OPERATOR_SELECTED_RTM_BLK_LINK_DECISION_AFTER_METADATA_EXPORT_NOT_GRANTED",
    "NEXT_FRONTIER_ONE_EXACT_PRODUCTION_BLK_LINK_WRAPPER_REQUEST_NOT_GRANTED",
    "NEXT_FRONTIER_POST_SINGLE_PRODUCTION_WRAPPER_RUN_OPERATOR_REVIEW_NOT_GRANTED",
    "NEXT_FRONTIER_REPEATABLE_TRUSTED_BLK_LINK_OPERATOR_USE_READY_PER_RUN_EXACT_APPROVAL_NOT_BLANKET_AUTHORITY",
    "NEXT_FRONTIER_OPERATOR_SELECTED_BLK_REQ_USE_OR_NEXT_COMPONENT",
    "NEXT_FRONTIER_KURONODE_BLK_REQ_EXACT_ID_MAPPING_OR_OPERATOR_USE_NOT_GRANTED",
    "NEXT_FRONTIER_BLK_REQ_CLOSED_NEXT_COMPONENT_SELECTION_NOT_GRANTED",
    "NEXT_FRONTIER_PRODUCTION_BLK_TEST_MCP_ORACLE_REQUEST_NOT_GRANTED",
)

EXPECTED_SURFACES = (
    "BLK-req legislative gateway",
    "Identity / relay provenance spine",
    "BLK-pipe blast shield",
    "Python adapter layer",
    "Validation profiles",
    "BLK-test",
    "Operator health / observability",
    "Codex live-dispatch ladder",
    "BEO publication path",
    "RTM / blk-link",
)

ALLOWED_STATES = {
    "overall_9_directive_guard_325_side_effect_decision_required",
    "blk_system_9_9_first_pass_322_review_ready_side_effects_separate",
    "beb_l2_route_artifact_boundary_323_hardened",
    "verified_loop_beo_publication_standing_development_approval_316_recorded_no_time_clock",
    "verified_loop_beo_publication_live_non_approval_315_reconciled_approval_required",
    "verified_loop_beo_publication_refresh_challenge_312_reconciled_approval_required",
    "verified_loop_beo_publication_approval_request_309_reconciled_capture_execution_required",
    "verified_loop_beo_publication_review_305_reconciled_approval_request_required",
    "exact_blk_test_oracle_verification_301_reconciled",
    "exact_quarantine_gated_blk003_loop_execution_297_reconciled",
    "reusable_blk003_loop_request_path_293_ready",
    "hitl_gateway_speculative_quarantine_gate_289_ready",
    "identity_relay_hitl_quarantine_gate_289_ready",
    "rtm_blk_link_drift_coverage_281_second_refresh_challenge_reconciled_approval_required",
    "rtm_blk_link_drift_coverage_278_refresh_challenge_reconciled_approval_required",
    "rtm_blk_link_drift_coverage_275_request_reconciled_approval_required",
    "exact_beo_publication_271_finality_reconciled_rtm_request_ready",
    "rtm_blk_link_drift_coverage_request_ready_after_exact_beo_publication",
    "exact_beo_publication_268_run_package_reconciled_execution_not_granted",
    "exact_beo_publication_265_approval_capture_reconciled_run_not_executed",
    "rtm_blk_link_drift_coverage_256_reconciled_beo_publication_required",
    "exact_beo_publication_260_approval_preflight_reconciled_not_granted",
    "reusable_beo_publication_251_per_run_exact_approval_ready",
    "production_blk_test_mcp_oracle_246_reconciled_verifier_only",
    "identity_relay_loop_evidence_285_ready",
    "reusable_blk003_loop_kernel_241_ready",
    "hitl_gateway_completion_slice_240_ready",
    "agent_a_context_packet_pr_235_merged",
    "repeat_kuronode_feature_drop_234_executed",
    "codex_progress_events_233_ready",
    "beb_l2_packet_helper_232_ready",
    "agent_a_header_pr_231_merged",
    "agent_a_header_drop_230_executed",
    "codex_private_bwrap_setup_229_descriptor_verified",
    "exact_kuronode_clean_worktree_feature_drop_228_executed",
    "external_codex_artifact_227_ready",
    "kuronode_worktree_static_profile_226_ready",
    "clean_worktree_manifest_225_ready",
    "ignored_residue_cleanup_plan_224_ready",
    "blk_req_metadata_bound_publication_request_127_complete",
    "blk_req_production_gateway_199_clean",
    "kuronode_blk_req_vault_bootstrap_200_ready",
    "kuronode_blk_req_bridge_203_clean",
    "local_guarded_enforcement",
    "blk_pipe_bounded_enforcement_206_closed",
    "beb_l2_preflight_guard_223_ready",
    "beb_l2_blk_pipe_codex_route_222_ready",
    "python_adapter_closed_209_clean",
    "fail_fast_convenience_layer",
    "repository_owned_local_profiles",
    "validation_profiles_closed_212_clean",
    "disabled_gated_evidence_only",
    "blk_test_optional_diagnostic_unblocked_213",
    "advisory_local_pilot",
    "review_ready_not_reusable_execution_authorized",
    "codex_config_containment_drill_216_recorded",
    "codex_bounded_feature_loop_218_recorded",
    "codex_native_sandbox_mitigation_219_recorded",
    "codex_native_sandbox_repair_recheck_220_recorded",
    "authoritative_beo_publication_finality_152_complete",
    "rtm_blk_link_protected_body_verification_evidence_integrated_177_hardened",
    "rtm_blk_link_protected_body_evidence_export_reconciled_182_clean",
    "reusable_blk_link_readiness_kernel_186_clean",
    "single_production_blk_link_wrapper_run_189_clean",
    "repeatable_trusted_blk_link_194_clean",
}

ALLOWED_MATURITIES = {
    "L3_OVERALL_9_TARGET_GUARDED_SIDE_EFFECT_DECISION_REQUIRED",
    "L3_BLK_SYSTEM_9_9_FIRST_PASS_REVIEW_READY_NOT_FINALITY",
    "L2_BEB_L2_ROUTE_ARTIFACT_BOUNDARY_HARDENED_NO_NEW_DISPATCH",
    "L3_VERIFIED_LOOP_BEO_PUBLICATION_STANDING_DEVELOPMENT_APPROVAL_RECORDED_NO_TIME_CLOCK",
    "L3_VERIFIED_LOOP_BEO_PUBLICATION_LIVE_NON_APPROVAL_RECONCILED_APPROVAL_REQUIRED",
    "L3_VERIFIED_LOOP_BEO_PUBLICATION_REFRESH_CHALLENGE_RECONCILED_APPROVAL_REQUIRED",
    "L3_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_REQUEST_READY_CAPTURE_EXECUTION_REQUIRED",
    "L3_VERIFIED_LOOP_BEO_PUBLICATION_REVIEW_READY_EXACT_APPROVAL_REQUEST_REQUIRED",
    "L3_EXACT_BLK_TEST_ORACLE_VERIFICATION_RECORDED_VERIFIER_ONLY_NO_TRANSPORT",
    "L3_EXACT_QUARANTINE_GATED_BLK003_LOOP_EXECUTION_RECORDED_READY_FOR_BLK_TEST",
    "L2_REUSABLE_BLK003_LOOP_REQUEST_PATH_READY_EXECUTION_NOT_GRANTED",
    "L2_HITL_QUARANTINE_GATE_READY_NO_DURABLE_MUTATION",
    "L2_RTM_BLK_LINK_DRIFT_COVERAGE_SECOND_REFRESH_CHALLENGE_RECONCILED_APPROVAL_REQUIRED_NOT_GRANTED",
    "L2_RTM_BLK_LINK_DRIFT_COVERAGE_REFRESH_CHALLENGE_RECONCILED_APPROVAL_REQUIRED_NOT_GRANTED",
    "L2_RTM_BLK_LINK_DRIFT_COVERAGE_REQUEST_RECONCILED_APPROVAL_REQUIRED_NOT_GRANTED",
    "L3_EXACT_BEO_PUBLICATION_FINALITY_RECORDED_RTM_REQUEST_READY",
    "L2_RTM_BLK_LINK_DRIFT_COVERAGE_REQUEST_READY_AFTER_EXACT_BEO_PUBLICATION",
    "L2_EXACT_BEO_RUN_PACKAGE_PREPARED_EXECUTION_APPROVAL_REQUIRED_NOT_GRANTED",
    "L2_EXACT_BEO_OPERATOR_TEXT_RECORDED_RUN_PACKAGE_REQUIRED_NOT_EXECUTED",
    "L2_RTM_BLK_LINK_DRIFT_COVERAGE_VERIFIER_READY_BEO_PUBLICATION_REQUIRED",
    "L2_EXACT_BEO_PUBLICATION_APPROVAL_PREFLIGHT_READY_NOT_GRANTED",
    "L2_REUSABLE_BEO_PUBLICATION_REVIEW_KERNEL_READY_PER_RUN_EXACT_APPROVAL",
    "L2_BLK_TEST_MCP_ORACLE_VERIFIER_ONLY_READY_NO_LIVE_MCP",
    "L2_IDENTITY_RELAY_LOOP_EVIDENCE_READY_NO_RUNTIME",
    "L2_REUSABLE_BLK003_LOOP_KERNEL_READY_NO_RUNTIME",
    "L2_HITL_GATEWAY_COMPLETION_SLICE_READY_EXACT_OPERATION_ONLY",
    "L2_REPEAT_KURONODE_DROP_EXECUTED_NOT_REUSABLE_AUTHORITY",
    "L2_CODEX_PROGRESS_EVENTS_READY_NOT_APPROVAL",
    "L2_BEB_L2_PACKET_HELPER_READY_NO_DISPATCH",
    "L2_KURONODE_PR_MERGED_NOT_NEW_MUTATION_AUTHORITY",
    "L2_EXACT_KURONODE_DROP_EXECUTED_NOT_REUSABLE_AUTHORITY",
    "L2_CODEX_PRIVATE_BWRAP_SETUP_DESCRIPTOR_VERIFIED_NOT_RUNTIME_AUTHORITY",
    "L2_EXACT_KURONODE_CLEAN_WORKTREE_FEATURE_DROP_EXECUTED_NOT_REUSABLE_AUTHORITY",
    "L2_EXTERNAL_CODEX_ARTIFACT_READY_NO_DISPATCH",
    "L2_KURONODE_WORKTREE_STATIC_PROFILE_READY_NO_DISPATCH",
    "L2_CLEAN_WORKTREE_MANIFEST_READY_NO_DISPATCH",
    "L2_IGNORED_RESIDUE_CLEANUP_PLAN_READY_NO_MUTATION",
    "L0_L1_METADATA_BOUND_BEO_PUBLICATION_PREREQUISITE_REQUEST_REVIEW_ONLY",
    "L2_BLK_REQ_PRODUCTION_GATEWAY_READY_EXACT_OPERATION_ONLY",
    "L2_KURONODE_BLK_REQ_SIBLING_VAULT_BLUEPRINT_READY_NOT_SOURCE_MUTATION",
    "L2_KURONODE_BLK_REQ_METADATA_ID_BRIDGE_CLOSED_NOT_SOURCE_MUTATION",
    "LOCAL_GUARDED_ENFORCEMENT_NOT_BROAD_AUTONOMY",
    "L2_BLK_PIPE_BOUNDED_NON_AUTHORIZING_ENFORCEMENT_SURFACE_CLOSED",
    "L2_BEB_L2_PREFLIGHT_GUARD_READY_EXACT_PAYLOAD_ONLY",
    "L2_BEB_L2_BLK_PIPE_CODEX_ROUTE_READY_EXACT_PAYLOAD_ONLY",
    "L2_PYTHON_ADAPTER_BOUNDED_PACKAGING_SURFACE_CLOSED",
    "L1_L2_STYLE_PREFLIGHT_ONLY",
    "MATURE_LOCAL_PROFILE_SUPPORT",
    "L2_VALIDATION_PROFILES_BOUNDED_LOCAL_EVIDENCE_CLOSED",
    "DISABLED_DESIGN_WITH_HISTORICAL_L3_EXCEPTION",
    "L2_BLK_TEST_OPTIONAL_DIAGNOSTIC_NOT_BLOCKING_FEATURE_LOOPS",
    "ADVISORY_PILOT_ONLY",
    "L0_L1_L2_STYLE_DISABLED_NO_REUSABLE_CODEX_DISPATCH",
    "L2_CODEX_PERMISSION_PROFILE_CONTAINMENT_CONTRACT_RECORDED_NOT_RUNTIME_AUTHORITY",
    "L2_CODEX_BOUNDED_FEATURE_LOOP_RECORDED_NOT_RUNTIME_AUTHORITY",
    "L2_CODEX_NATIVE_SANDBOX_MITIGATION_RECORDED_NOT_RUNTIME_AUTHORITY",
    "L2_CODEX_NATIVE_SANDBOX_REPAIR_RECHECK_RECORDED_NOT_REUSABLE_AUTHORITY",
    "L3_AUTHORITATIVE_BEO_PUBLICATION_SIGNER_STORAGE_LEDGER_FINALITY_COMPLETE",
    "L2_PROTECTED_BODY_HASH_VERIFICATION_EVIDENCE_INTEGRATED_HARDENED_NOT_REUSABLE_AUTHORITY",
    "L2_PROTECTED_BODY_EVIDENCE_METADATA_EXPORT_RECONCILED_NOT_REUSABLE_AUTHORITY",
    "L2_REUSABLE_BLK_LINK_READINESS_KERNEL_READY_PER_RUN_EXACT_APPROVAL_REQUIRED",
    "L2_SINGLE_PRODUCTION_BLK_LINK_WRAPPER_RUN_EXECUTED_EXACT_ONCE_NO_REUSE",
    "L2_REPEATABLE_TRUSTED_BLK_LINK_OPERATOR_USE_READY_PER_RUN_EXACT_APPROVAL",
}

TOP_LEVEL_KEYS = {
    "index_id",
    "index_status",
    "roadmap_source",
    "maturity",
    "surfaces",
    "evaluation",
    "validation_errors",
    *DENIED_FLAGS,
}

SURFACE_KEYS = {
    "surface",
    "state",
    "maturity",
    "governing_docs",
    "authority_cutline",
}

DEFAULT_SURFACES = (
    {
        "surface": "BLK-req legislative gateway",
        "state": "hitl_gateway_speculative_quarantine_gate_289_ready",
        "maturity": "L2_HITL_QUARANTINE_GATE_READY_NO_DURABLE_MUTATION",
        "governing_docs": ["BLK-077", "BLK-079", "BLK-116", "BLK-120", "BLK-122", "BLK-123"],
        "authority_cutline": (
            "BLK_SYSTEM_240_HITL_GATEWAY_COMPLETION_SLICE_READY now has "
            "BLK_SYSTEM_286_SPECULATIVE_QUARANTINE_APPROVAL_CONTRACT_READY through "
            "BLK_SYSTEM_289_PROMOTION_PURGE_STALE_GATE_READY timing evidence: Discord component HITL, quarantine result hashes, and promote/purge/stale gates. "
            "The gateway still preserves exact BLK-req IDs and per-operation decisions only. "
            "No Kuronode source/Git mutation, no broad Kuronode doc scan, no protected-body migration, no broad active-vault body scan, no body access without exact ID, no BEO/RTM/runtime/tooling/mutation authority."
        ),
    },
    {
        "surface": "Identity / relay provenance spine",
        "state": "identity_relay_hitl_quarantine_gate_289_ready",
        "maturity": "L2_HITL_QUARANTINE_GATE_READY_NO_DURABLE_MUTATION",
        "governing_docs": ["BLK-001", "BLK-003", "BLK-077", "BLK-079", "BLK-122", "BLK-123"],
        "authority_cutline": (
            "BLK_SYSTEM_286_SPECULATIVE_QUARANTINE_APPROVAL_CONTRACT_READY, BLK_SYSTEM_287_HITL_INTERACTION_IDENTITY_RELAY_EVIDENCE_READY, "
            "BLK_SYSTEM_288_SPECULATIVE_QUARANTINE_EVIDENCE_READY, and BLK_SYSTEM_289_PROMOTION_PURGE_STALE_GATE_READY bind Discord HITL, blk-id, blk-relay, quarantine hashes, and stale-target checks. "
            "No relay network runtime, no message dispatch, no approval reuse, no durable target/source/Git mutation, no BEO/RTM/blk-link, no protected-body access, and no production-isolation authority."
        ),
    },
    {
        "surface": "BLK-pipe blast shield",
        "state": "blk_pipe_bounded_enforcement_206_closed",
        "maturity": "L2_BLK_PIPE_BOUNDED_NON_AUTHORIZING_ENFORCEMENT_SURFACE_CLOSED",
        "governing_docs": ["BLK-003", "BLK-004", "BLK-077", "BLK-079", "BLK-112", "BLK-113", "BLK-114", "BLK-115"],
        "authority_cutline": (
            "BLK_SYSTEM_206_BLK_PIPE_BOUNDED_ENFORCEMENT_RECONCILED_CLEAN after "
            "BLK_SYSTEM_205_BLK_PIPE_BOUNDED_ENFORCEMENT_CONTRACT_READY and "
            "BLK_SYSTEM_204_BLK_PIPE_SURFACE_REVIEW_READY. BLK-pipe is a bounded non-authorizing enforcement surface for "
            "structured validation-profile argv, failure/denial/cleanup evidence, and exact allowlists. No broad dispatch, no target/source/Git mutation, no runtime tooling, and no production-isolation claim."
        ),
    },
    {
        "surface": "Python adapter layer",
        "state": "exact_quarantine_gated_blk003_loop_execution_297_reconciled",
        "maturity": "L3_EXACT_QUARANTINE_GATED_BLK003_LOOP_EXECUTION_RECORDED_READY_FOR_BLK_TEST",
        "governing_docs": ["BLK-016", "BLK-021", "BLK-077", "BLK-079", "BLK-124", "BLK-125"],
        "authority_cutline": (
            "BLK_SYSTEM_297_EXACT_QUARANTINE_GATED_BLK003_LOOP_EXECUTION_RECONCILED after BLK_SYSTEM_294_EXACT_QUARANTINE_GATED_BLK003_LOOP_EXECUTION_PACKAGE_READY, BLK_SYSTEM_295_FRESH_TARGET_WORKTREE_SANDBOX_PREFLIGHT_READY, and BLK_SYSTEM_296_QUARANTINE_BOUNDED_BLK003_LOOP_EXECUTION_RECORDED consumes BLK_SYSTEM_293_REUSABLE_BLK003_LOOP_REQUEST_PATH_RECONCILED. "
            "It records one quarantine-contained loop report with target-hash recheck, private-bwrap descriptor, failure ceiling 3, cleanup evidence, and BEO draft hash. "
            "no reusable Codex dispatch, no broad BLK-pipe dispatch, no durable target/source/Git mutation, no protected-body access, no BEO closeout execution, no RTM, no production BLK-test MCP transport, no production blk-link, no package-manager, no host containment claim, or no production-isolation authority."
        ),
    },
    {
        "surface": "Validation profiles",
        "state": "beb_l2_route_artifact_boundary_323_hardened",
        "maturity": "L2_BEB_L2_ROUTE_ARTIFACT_BOUNDARY_HARDENED_NO_NEW_DISPATCH",
        "governing_docs": ["BLK-077", "BLK-079", "BLK-112", "BLK-113", "BLK-114", "BLK-115"],
        "authority_cutline": (
            "BLK_SYSTEM_323_BEB_L2_ROUTE_ARTIFACT_BOUNDARY_HARDENED blocks protected BEB/L2 artifact paths and contains processed/failed inbox dirs under trusted roots. "
            "BLK_SYSTEM_226_KURONODE_WORKTREE_STATIC_PROFILE_READY and BLK_SYSTEM_212_VALIDATION_PROFILE_RECONCILED_CLEAN remain the local profile base (`git diff --check -- .`). "
            "local whitespace/static evidence only: no package manager, no network, no runtime, no mutation, no publication, no RTM, no tooling, no production-isolation, no BLK-pipe dispatch, and no BLK-test MCP authority."
        ),
    },
    {
        "surface": "BLK-test",
        "state": "exact_blk_test_oracle_verification_301_reconciled",
        "maturity": "L3_EXACT_BLK_TEST_ORACLE_VERIFICATION_RECORDED_VERIFIER_ONLY_NO_TRANSPORT",
        "governing_docs": ["BLK-017", "BLK-018", "BLK-019", "BLK-020", "BLK-077", "BLK-079", "BLK-126"],
        "authority_cutline": (
            "BLK_SYSTEM_301_EXACT_BLK_TEST_ORACLE_VERIFICATION_RECONCILED after BLK_SYSTEM_298_EXACT_BLK_TEST_ORACLE_VERIFICATION_CONTRACT_READY, "
            "BLK_SYSTEM_299_EXACT_BLK_TEST_ORACLE_VERIFICATION_PREFLIGHT_READY, and BLK_SYSTEM_300_EXACT_BLK_TEST_ORACLE_VERIFICATION_RECORDED consumes BLK_SYSTEM_297_EXACT_QUARANTINE_GATED_BLK003_LOOP_EXECUTION_RECONCILED and BLK_SYSTEM_246_PRODUCTION_BLK_TEST_MCP_ORACLE_RECONCILED_VERIFIER_ONLY. "
            "BLK-test remains verifier-only; transport remains disabled and PASS is not approval. No planner/dispatcher/source-of-truth role, source/Git mutation, BEO/RTM/blk-link, drift/coverage truth, tooling, or protected-body authority."
        ),
    },
    {
        "surface": "Operator health / observability",
        "state": "advisory_local_pilot",
        "maturity": "ADVISORY_PILOT_ONLY",
        "governing_docs": ["BLK-031", "BLK-077", "BLK-079"],
        "authority_cutline": "Health and observability outputs are advisory. A PASS is not execution approval, publication authority, RTM truth, coverage truth, sandbox evidence, or protected-body access authority.",
    },
    {
        "surface": "Codex live-dispatch ladder",
        "state": "codex_private_bwrap_setup_229_descriptor_verified",
        "maturity": "L2_CODEX_PRIVATE_BWRAP_SETUP_DESCRIPTOR_VERIFIED_NOT_RUNTIME_AUTHORITY",
        "governing_docs": ["BLK-040", "BLK-041", "BLK-042", "BLK-043", "BLK-044", "BLK-077", "BLK-079", "BLK-121", "BLK-SYSTEM-216", "BLK-SYSTEM-217", "BLK-SYSTEM-218", "BLK-SYSTEM-219", "BLK-SYSTEM-220", "BLK-SYSTEM-229"],
        "authority_cutline": (
            "BLK_SYSTEM_229_PRIVATE_BWRAP_WORKSPACE_WRITE_SETUP_READY records a private bwrap AppArmor setup/runbook for Codex `workspace-write` while keeping kernel.apparmor_restrict_unprivileged_userns=1; the BLK-SYSTEM-230 run verified `/opt/blk-system/codex-bwrap/bwrap`, loaded `blk-codex-bwrap`, and used descriptor `READY`. "
            "BLK_SYSTEM_220_NATIVE_CODEX_SANDBOX_REPAIR_RECHECK_RECORDED remains the workspace-write smoke passed only under runtime host-admin AppArmor userns relaxation anchor. "
            "No reusable Codex dispatch, persistent host-wide relaxation, BLK-pipe dispatch, broad source mutation, package/network/model/browser/cyber tooling, or production-isolation claim."
        ),
    },
    {
        "surface": "BEO publication path",
        "state": "overall_9_directive_guard_325_side_effect_decision_required",
        "maturity": "L3_OVERALL_9_TARGET_GUARDED_SIDE_EFFECT_DECISION_REQUIRED",
        "governing_docs": ["BLK-022", "BLK-077", "BLK-079", "BLK-127", "BLK-128"],
        "authority_cutline": (
            "BLK_SYSTEM_325_OVERALL_9_DIRECTIVE_GUARDED: 7/10 practical baseline; 9/10 target; "
            f"{NEXT_FRONTIER_325}; blk325={EXPECTED_325_OVERALL_GUARD_HASH}. "
            "BLK_SYSTEM_322_ROOT_DOCTRINE_ROADMAP_FIRST_PASS_DONE_FOR_9_9_REVIEW_READY: 9.9/10 theory review; "
            f"{NEXT_FRONTIER_322}; blk321={EXPECTED_321_RECONCILIATION_HASH}. "
            "BLK_SYSTEM_321_9_OF_10_DEVELOPMENT_UNBLOCK_RECONCILED through BLK_SYSTEM_316_STANDING_BLK_SYSTEM_DEVELOPMENT_APPROVAL_RECORDED (8.5/10 repo development ready) repo-only. "
            "no run-ID reservation/consumption, no BEO publication, no reusable BEO publication, no signer/storage/ledger reuse, no RTM, no production blk-link, no protected-body access, no runtime/tooling, no target/source/Git mutation."
        )
    },
    {
        "surface": "RTM / blk-link",
        "state": "rtm_blk_link_drift_coverage_281_second_refresh_challenge_reconciled_approval_required",
        "maturity": "L2_RTM_BLK_LINK_DRIFT_COVERAGE_SECOND_REFRESH_CHALLENGE_RECONCILED_APPROVAL_REQUIRED_NOT_GRANTED",
        "governing_docs": ["BLK-023", "BLK-077", "BLK-079", "BLK-140", "BLK-141", "BLK-142", "BLK-143", "BLK-144"],
        "authority_cutline": (
            "BLK_SYSTEM_281_RTM_BLK_LINK_DRIFT_COVERAGE_SECOND_REFRESH_CHALLENGE_RECONCILED after "
            "BLK_SYSTEM_279_RTM_BLK_LINK_DRIFT_COVERAGE_REFRESHED_CHALLENGE_EXPIRED_ATTEMPT_RECORDED and "
            "BLK_SYSTEM_280_RTM_BLK_LINK_DRIFT_COVERAGE_SECOND_REFRESH_APPROVE_CHALLENGE_READY. "
            "BLK_SYSTEM_278_RTM_BLK_LINK_DRIFT_COVERAGE_REFRESH_CHALLENGE_RECONCILED is prior refresh context; "
            "BLK_SYSTEM_194_REPEATABLE_TRUSTED_BLK_LINK_RECONCILED_CLEAN remains boxed. "
            "The second refreshed bounded short Approve challenge is not approved. No blanket production `blk-link`, no RTM generation, no reusable RTM generation, no run-ID reservation or consumption, no drift rejection, no coverage truth, no protected-body text return, no target/source/Git mutation."
        ),
    },
)


def build_current_state_authority_index(surfaces=None):
    record = {
        "index_id": INDEX_ID,
        "index_status": INDEX_STATUS,
        "roadmap_source": "BLK-077",
        "maturity": MATURITY,
        "surfaces": deepcopy(list(DEFAULT_SURFACES if surfaces is None else surfaces)),
        "evaluation": READY,
        "validation_errors": [],
    }
    for flag in DENIED_FLAGS:
        record[flag] = False
    return record


def validate_current_state_authority_index(record):
    errors = []
    if not isinstance(record, dict):
        return ["record must be a dictionary"]

    unknown_top_keys = sorted(set(record) - TOP_LEVEL_KEYS)
    for key in unknown_top_keys:
        errors.append(f"unsupported top-level key {key!r}")

    expected_scalars = {
        "index_id": INDEX_ID,
        "index_status": INDEX_STATUS,
        "roadmap_source": "BLK-077",
        "maturity": MATURITY,
    }
    for key, expected in expected_scalars.items():
        if record.get(key) != expected:
            errors.append(f"{key} must be {expected!r}")

    if record.get("evaluation") not in {READY, BLOCKED, None}:
        errors.append("evaluation must be a current-state index status")
    if "validation_errors" in record and not isinstance(record.get("validation_errors"), list):
        errors.append("validation_errors must be a list")

    for flag in DENIED_FLAGS:
        if record.get(flag) is not False:
            errors.append(f"{flag} must remain false")

    surfaces = record.get("surfaces")
    if not isinstance(surfaces, list):
        errors.append("surfaces must be a list")
        surfaces = []

    names = []
    for index, surface in enumerate(surfaces):
        if not isinstance(surface, dict):
            errors.append(f"surface[{index}] must be a dictionary")
            continue
        name = surface.get("surface")
        names.append(name)
        for key in sorted(set(surface) - SURFACE_KEYS):
            errors.append(f"surface {name!r} has unsupported key {key!r}")
        if name not in EXPECTED_SURFACES:
            errors.append(f"unexpected surface {name!r}")
        if surface.get("state") not in ALLOWED_STATES:
            errors.append(f"unsupported state {surface.get('state')!r} for surface {name!r}")
        if surface.get("maturity") not in ALLOWED_MATURITIES:
            errors.append(f"unsupported maturity {surface.get('maturity')!r} for surface {name!r}")
        docs = surface.get("governing_docs")
        if not isinstance(docs, list) or not docs:
            errors.append(f"surface {name!r} governing_docs must be a non-empty list")
        elif "BLK-077" not in docs:
            errors.append(f"surface {name!r} must cite BLK-077")
        cutline = surface.get("authority_cutline")
        if not isinstance(cutline, str) or not cutline.strip():
            errors.append(f"surface {name!r} authority_cutline must be a non-empty string")
        elif len(cutline) > 900:
            errors.append(f"surface {name!r} authority_cutline exceeds lean current-state length")

    if set(names) != set(EXPECTED_SURFACES):
        errors.append("surfaces must match the lean current-state surface set exactly")
    if len(names) != len(set(names)):
        errors.append("surfaces must not contain duplicates")

    scan_candidate = {k: v for k, v in record.items() if k not in DENIED_FLAGS}
    errors.extend(scan_for_authority_laundering(scan_candidate, denied_keys=DENIED_FLAGS))
    return errors


def validate_active_current_state_docs(roadmap_text, index_text):
    errors = []
    if not isinstance(roadmap_text, str) or not isinstance(index_text, str):
        return ["active docs must be strings"]
    combined = f"{roadmap_text}\n{index_text}"

    for marker in ACTIVE_DOC_REQUIRED_MARKERS:
        if marker not in combined:
            errors.append(f"active docs missing required marker {marker!r}")
    for marker in STALE_ACTIVE_DOC_MARKERS:
        if marker in combined:
            errors.append(f"active docs contain stale marker {marker!r}")

    if set(DOC_DENIAL_MARKERS) != set(DENIED_FLAGS):
        errors.append("DOC_DENIAL_MARKERS must exactly cover DENIED_FLAGS")

    for flag in DENIED_FLAGS:
        markers = DOC_DENIAL_MARKERS.get(flag, ())
        if not markers:
            errors.append(f"{flag} has no active-doc denial marker")
            continue
        if not any(marker in combined for marker in markers):
            errors.append(f"{flag} missing active-doc denial marker {markers!r}")
    errors.extend(scan_for_authority_laundering(combined, path="active_docs", denied_keys=DENIED_FLAGS))
    return errors


def evaluate_current_state_authority_index(record=None):
    candidate = build_current_state_authority_index() if record is None else deepcopy(record)
    errors = validate_current_state_authority_index(candidate)
    candidate["evaluation"] = BLOCKED if errors else READY
    candidate["validation_errors"] = errors
    for flag in DENIED_FLAGS:
        candidate[flag] = False
    return candidate
