from pathlib import Path
import re
import unittest

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
BLK077 = DOCS / "BLK-077_blk-system-post-078-roadmap.md"
BLK079 = DOCS / "BLK-079_post-078-current-state-authority-index.md"
ROOT_DOCS = [
    DOCS / "BLK-001_blk-system-master-architecture.md",
    DOCS / "BLK-002_blk-req-artifact-lifecycle.md",
    DOCS / "BLK-003_blk-pipe-blk-test-orchestration.md",
    DOCS / "BLK-004_blk-pipe-v47-architecture-suite.md",
    DOCS / "BLK-005_blk-req-specification.md",
    DOCS / "BLK-006_blk-req-implementation-brief.md",
]


class LeanDocumentationPolicyTest(unittest.TestCase):
    def test_active_roadmap_is_occam_focused_and_controls_doc_burden(self):
        text = BLK077.read_text()
        required = [
            "LEAN_DOCUMENTATION_MODEL_ACTIVE",
            "NO_BLK_DOC_PER_SPRINT",
            "ONE_OUTCOME_PER_SPRINT_NO_TASK_OUTCOME_DOCS",
            "BLK_001_TO_006_FIXED_OVERVIEW_NOT_SPRINT_STATE",
            "ROADMAP_OCCAM_PRODUCTION_ONLY",
            "BLK_SYSTEM_333_RTM_BLK_LINK_TRACE_CLOSURE_RECONCILED",
            "NEXT_FRONTIER_ONE_EXACT_BEO_TO_RTM_BLK_LINK_TRACE_CLOSED_REUSABLE_AUTHORITY_NOT_GRANTED",
            "sha256:0cf714e86b0dcff83460dcaaa34597eaf8ad887934de21019fc2107ebef6dfa4",
            "BLK_SYSTEM_332_RTM_BLK_LINK_TRACE_CLOSURE_RECORDED_FROM_OFFICIAL_BEO_METADATA",
            "sha256:d353513147b0fb5ec6ea7dc60d7b16701b280a3c3bb80c6e943dce5bcde83ef4",
            "BLK_SYSTEM_331_VERIFIED_LOOP_BEO_PUBLICATION_FINALITY_RECONCILED",
            "sha256:7b078329fe657b34ccbc0343ad73d49cb13a9c4e0ab19132206efd1b093b28bf",
            "BLK_SYSTEM_330_VERIFIED_LOOP_BEO_PUBLICATION_SIDE_EFFECT_PACKAGE_EXECUTED",
            "sha256:64074ea37ce818197d6a4a376725ac86bdb6958da5b3a175c3aadad1fa19a4ed",
            "BLK_SYSTEM_329_VERIFIED_LOOP_BEO_PUBLICATION_BOUNDED_EXECUTION_KERNEL_READY",
            "NEXT_FRONTIER_VERIFIED_LOOP_BEO_PUBLICATION_BOUNDED_EXECUTION_KERNEL_READY_EXACT_SIDE_EFFECT_PACKAGE_REQUIRED",
            "sha256:b0562eeb3d2b2b65e4f95b2ce396c2004ddf47e443452152e69137a85336284a",
            "BLK_SYSTEM_328_DEVELOPMENT_AUTHORITY_DISTINCTION_RECORDED",
            "NEXT_FRONTIER_BLK_SYSTEM_DEVELOPMENT_WORK_UNBLOCKED_INTERNAL_GATES_DISTINGUISHED",
            "sha256:57cdc2e0fdb4c4d5fe31ec3731eccecb5a3f34e783c6f7c51f27c0101b2bdf39",
            "BLK_SYSTEM_327_BROAD_SIDE_EFFECT_APPROVAL_REJECTED",
            "NEXT_FRONTIER_EXACT_BEO_PUBLICATION_DECISION_SPLIT_REQUIRED_BROAD_APPROVAL_REJECTED_NOT_GRANTED",
            "sha256:d18946139c9c9565aa542db12edb816bc01dcbf67d1bb62ff53232c17a11e1b0",
            "BLK_SYSTEM_326_FUNCTIONAL_9_EXECUTION_LADDER_READY",
            "NEXT_FRONTIER_FUNCTIONAL_9_EXACT_BEO_SIDE_EFFECT_DECISION_REQUIRED_NOT_GRANTED",
            "sha256:05bf576178f5e848c2b98a70eae42873916f00ee816ce51f3744d575466cae4a",
            "BLK_SYSTEM_321_9_OF_10_DEVELOPMENT_UNBLOCK_RECONCILED",
            "NEXT_FRONTIER_BLK_SYSTEM_9_OF_10_REPO_DEVELOPMENT_READY_SIDE_EFFECT_APPROVALS_SEPARATE_NOT_GRANTED",
            "BLK_SYSTEM_320_9_OF_10_READINESS_MATRIX_READY",
            "BLK_SYSTEM_319_DEVELOPMENT_DIRECTIVE_GUARD_RECORDED",
            "BLK_SYSTEM_318_EXACT_NO_CLOCK_SIDE_EFFECT_REQUEST_READY",
            "BLK_SYSTEM_317_9_OF_10_DEVELOPMENT_FRONTIER_BOUND",
            "BLK_SYSTEM_316_STANDING_BLK_SYSTEM_DEVELOPMENT_APPROVAL_RECORDED",
            "BLK_SYSTEM_315_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_LIVE_REFRESH_NON_APPROVAL_RECONCILED",
            "BLK_SYSTEM_314_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_SHORT_APPROVE_GUARD_READY",
            "BLK_SYSTEM_313_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_LIVE_REFRESH_GENERIC_DIRECTIVE_RECORDED",
            "BLK_SYSTEM_312_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_REFRESH_CHALLENGE_RECONCILED",
            "BLK_SYSTEM_311_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_REFRESH_APPROVE_CHALLENGE_READY",
            "BLK_SYSTEM_310_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_CHALLENGE_EXPIRED_ATTEMPT_RECORDED",
            "NEXT_FRONTIER_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_CAPTURE_AND_BOUNDED_EXECUTION_REQUIRED_NOT_GRANTED",
            "BLK_SYSTEM_309_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_REQUEST_RECONCILED",
            "BLK_SYSTEM_308_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_CHALLENGE_RECORDED",
            "BLK_SYSTEM_307_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_REQUEST_CONTRACT_READY",
            "BLK_SYSTEM_306_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_REQUEST_READY",
            "NEXT_FRONTIER_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_APPROVAL_REQUEST_REQUIRED_NOT_GRANTED",
            "BLK_SYSTEM_305_VERIFIED_LOOP_BEO_PUBLICATION_REVIEW_RECONCILED",
            "BLK_SYSTEM_304_VERIFIED_LOOP_BEO_PUBLICATION_REVIEW_RECORDED",
            "BLK_SYSTEM_303_VERIFIED_LOOP_BEO_PUBLICATION_REVIEW_CONTRACT_READY",
            "BLK_SYSTEM_302_VERIFIED_LOOP_BEO_PUBLICATION_REVIEW_REQUEST_READY",
            "NEXT_FRONTIER_VERIFIED_LOOP_BEO_PUBLICATION_REVIEW_REQUIRED_NOT_GRANTED",
            "BLK_SYSTEM_301_EXACT_BLK_TEST_ORACLE_VERIFICATION_RECONCILED",
            "BLK_SYSTEM_300_EXACT_BLK_TEST_ORACLE_VERIFICATION_RECORDED",
            "BLK_SYSTEM_299_EXACT_BLK_TEST_ORACLE_VERIFICATION_PREFLIGHT_READY",
            "BLK_SYSTEM_298_EXACT_BLK_TEST_ORACLE_VERIFICATION_CONTRACT_READY",
            "NEXT_FRONTIER_EXACT_BLK_TEST_ORACLE_VERIFICATION_AFTER_LOOP_EXECUTION_REQUIRED_NOT_GRANTED",
            "BLK_SYSTEM_297_EXACT_QUARANTINE_GATED_BLK003_LOOP_EXECUTION_RECONCILED",
            "BLK_SYSTEM_296_QUARANTINE_BOUNDED_BLK003_LOOP_EXECUTION_RECORDED",
            "BLK_SYSTEM_295_FRESH_TARGET_WORKTREE_SANDBOX_PREFLIGHT_READY",
            "BLK_SYSTEM_294_EXACT_QUARANTINE_GATED_BLK003_LOOP_EXECUTION_PACKAGE_READY",
            "NEXT_FRONTIER_EXACT_QUARANTINE_GATED_BLK003_LOOP_EXECUTION_PACKAGE_REQUIRED_NOT_GRANTED",
            "BLK_SYSTEM_293_REUSABLE_BLK003_LOOP_REQUEST_PATH_RECONCILED",
            "BLK_SYSTEM_292_QUARANTINE_GATED_REQUEST_PREFLIGHT_READY",
            "BLK_SYSTEM_291_BEB_L2_ROUTE_REQUEST_BINDING_READY",
            "BLK_SYSTEM_290_BLK003_LOOP_REQUEST_CONTRACT_READY",
            "NEXT_FRONTIER_REUSABLE_BLK003_LOOP_REQUEST_PATH_WITH_QUARANTINE_GATE_NOT_GRANTED",
            "BLK_SYSTEM_289_PROMOTION_PURGE_STALE_GATE_READY",
            "BLK_SYSTEM_288_SPECULATIVE_QUARANTINE_EVIDENCE_READY",
            "BLK_SYSTEM_287_HITL_INTERACTION_IDENTITY_RELAY_EVIDENCE_READY",
            "BLK_SYSTEM_286_SPECULATIVE_QUARANTINE_APPROVAL_CONTRACT_READY",
            "NEXT_FRONTIER_HITL_GATEWAY_IDENTITY_RELAY_WIRING_NOT_GRANTED",
            "BLK_SYSTEM_285_IDENTITY_RELAY_LOOP_EVIDENCE_READY",
            "BLK_SYSTEM_284_BLK_RELAY_ENVELOPE_CONTRACT_READY",
            "BLK_SYSTEM_283_BLK_IDENTITY_SPINE_CONTRACT_READY",
            "NEXT_FRONTIER_RTM_BLK_LINK_DRIFT_COVERAGE_SECOND_REFRESHED_BOUND_APPROVE_REQUIRED_NOT_GRANTED",
            "BLK_SYSTEM_282_AGENT_A_REQUIREMENT_CONTEXT_SUMMARY_FEATURE_DROP_EXECUTED",
            "BLK_SYSTEM_281_RTM_BLK_LINK_DRIFT_COVERAGE_SECOND_REFRESH_CHALLENGE_RECONCILED",
            "BLK_SYSTEM_280_RTM_BLK_LINK_DRIFT_COVERAGE_SECOND_REFRESH_APPROVE_CHALLENGE_READY",
            "BLK_SYSTEM_279_RTM_BLK_LINK_DRIFT_COVERAGE_REFRESHED_CHALLENGE_EXPIRED_ATTEMPT_RECORDED",
            "NEXT_FRONTIER_RTM_BLK_LINK_DRIFT_COVERAGE_REFRESHED_BOUND_APPROVE_REQUIRED_NOT_GRANTED",
            "BLK_SYSTEM_278_RTM_BLK_LINK_DRIFT_COVERAGE_REFRESH_CHALLENGE_RECONCILED",
            "BLK_SYSTEM_277_RTM_BLK_LINK_DRIFT_COVERAGE_REFRESH_APPROVE_CHALLENGE_READY",
            "BLK_SYSTEM_276_RTM_BLK_LINK_DRIFT_COVERAGE_EXPIRED_APPROVE_ATTEMPT_RECORDED",
            "NEXT_FRONTIER_RTM_BLK_LINK_DRIFT_COVERAGE_BOUND_APPROVE_OR_EXACT_TEXT_REQUIRED_NOT_GRANTED",
            "BLK_SYSTEM_275_RTM_BLK_LINK_DRIFT_COVERAGE_REQUEST_RECONCILED",
            "BLK_SYSTEM_274_RTM_BLK_LINK_DRIFT_COVERAGE_APPROVAL_PREFLIGHT_BLOCKED",
            "BLK_SYSTEM_273_RTM_BLK_LINK_DRIFT_COVERAGE_APPROVE_CHALLENGE_READY",
            "BLK_SYSTEM_272_RTM_BLK_LINK_DRIFT_COVERAGE_REQUEST_READY",
            "NEXT_FRONTIER_RTM_BLK_LINK_DRIFT_COVERAGE_REQUEST_READY_AFTER_EXACT_BEO_PUBLICATION",
            "BLK_SYSTEM_271_EXACT_BEO_PUBLICATION_FINALITY_RECONCILED",
            "BLK_SYSTEM_270_EXACT_BEO_PUBLICATION_FINALITY_RECORD_EXECUTED",
            "BLK_SYSTEM_269_EXACT_BEO_PUBLICATION_EXECUTION_APPROVAL_CAPTURED",
            "NEXT_FRONTIER_EXACT_BEO_PUBLICATION_EXECUTION_APPROVAL_REQUIRED_NOT_GRANTED",
            "BLK_SYSTEM_268_EXACT_BEO_PUBLICATION_RUN_PACKAGE_RECONCILED",
            "BLK_SYSTEM_267_EXACT_BEO_PUBLICATION_RUN_PREFLIGHT_BLOCKED",
            "BLK_SYSTEM_266_EXACT_BEO_PUBLICATION_RUN_PACKAGE_READY",
            "NEXT_FRONTIER_EXACT_BEO_PUBLICATION_RUN_PACKAGE_REQUIRED_NOT_EXECUTED",
            "BLK_SYSTEM_265_EXACT_BEO_PUBLICATION_APPROVAL_CAPTURE_RECONCILED",
            "BLK_SYSTEM_264_EXACT_BEO_PUBLICATION_OPERATOR_APPROVAL_CAPTURED",
            "BLK_SYSTEM_263_SPRINT_PACKAGE_SELECTION_GATE_READY",
            "BLK_SYSTEM_262_SPRINT_PACKAGE_GRANULARITY_CONTRACT_READY",
            "BLK_SYSTEM_261_SPRINT_PACKAGE_FRONTIER_REVIEW_READY",
            "BLK_SYSTEM_260_EXACT_BEO_PUBLICATION_APPROVAL_RECONCILED_NOT_GRANTED",
            "BLK_SYSTEM_259_EXACT_BEO_PUBLICATION_APPROVAL_PREFLIGHT_RECORDED",
            "BLK_SYSTEM_258_EXACT_BEO_PUBLICATION_OPERATOR_APPROVAL_CONTRACT_READY",
            "BLK_SYSTEM_257_EXACT_BEO_PUBLICATION_RUN_REQUEST_READY",
                    "BLK_SYSTEM_251_REUSABLE_BEO_PUBLICATION_RECONCILED_PER_RUN_EXACT_APPROVAL_READY",
            "BLK_SYSTEM_250_BLK003_LOOP_BEO_PUBLICATION_REVIEW_INTEGRATION_READY",
            "BLK_SYSTEM_249_EXACT_BEO_PUBLICATION_DRY_RUN_REVIEW_READY",
            "BLK_SYSTEM_248_REUSABLE_BEO_PUBLICATION_CONTRACT_READY",
            "BLK_SYSTEM_247_REUSABLE_BEO_PUBLICATION_REQUEST_SCOPED",
            "BLK_SYSTEM_246_PRODUCTION_BLK_TEST_MCP_ORACLE_RECONCILED_VERIFIER_ONLY",
            "BLK_SYSTEM_245_BLK003_LOOP_ORACLE_EVIDENCE_INTEGRATION_READY",
            "BLK_SYSTEM_244_METADATA_ONLY_BLK_TEST_ORACLE_FIXTURE_READY",
            "BLK_SYSTEM_243_PRODUCTION_BLK_TEST_MCP_ORACLE_CONTRACT_READY",
            "BLK_SYSTEM_242_PRODUCTION_BLK_TEST_MCP_ORACLE_REQUEST_SCOPED",
            "BLK_SYSTEM_241_REUSABLE_BLK003_LOOP_KERNEL_READY",
            "BLK_SYSTEM_240_HITL_GATEWAY_COMPLETION_SLICE_READY",
            "BLK_SYSTEM_239_BLK_ID_RELAY_SCOPE_DECIDED",
            "BLK_SYSTEM_238_ROOT_DOCTRINE_DEVIATION_OVERLAY_READY",
            "BLK_SYSTEM_237_KURONODE_ROUTE_SELECTION_READY",
            "BLK_SYSTEM_235_AGENT_A_CONTEXT_PACKET_PR_MERGED",
            "BLK_SYSTEM_234_REPEAT_KURONODE_FEATURE_DROP_EXECUTED",
            "BLK_SYSTEM_233_CODEX_PROGRESS_EVENTS_READY",
            "BLK_SYSTEM_232_BEB_L2_PACKET_HELPER_READY",
            "BLK_SYSTEM_231_AGENT_A_HEADER_PR_MERGED",
            "BLK_SYSTEM_230_AGENT_A_HEADER_DROP_EXECUTED",
            "BLK_SYSTEM_229_PRIVATE_BWRAP_WORKSPACE_WRITE_SETUP_READY",
            "BLK_SYSTEM_228_EXACT_KURONODE_CLEAN_WORKTREE_FEATURE_DROP_EXECUTED",
            "BLK_SYSTEM_227_EXTERNAL_CODEX_ARTIFACT_READY",
            "BLK_SYSTEM_226_KURONODE_WORKTREE_STATIC_PROFILE_READY",
            "BLK_SYSTEM_225_CLEAN_WORKTREE_MANIFEST_READY",
            "BLK_SYSTEM_224_IGNORED_RESIDUE_CLEANUP_PLAN_READY",
            "BLK_SYSTEM_223_BEB_L2_PREFLIGHT_GUARD_READY",
            "BLK_SYSTEM_222_BEB_L2_BLK_PIPE_CODEX_ROUTE_READY",
            "BLK_SYSTEM_221_FOURTH_BOUNDED_KURONODE_FEATURE_LOOP_EXECUTED",
            "BLK_SYSTEM_220_NATIVE_CODEX_SANDBOX_REPAIR_RECHECK_RECORDED",
            "BLK_SYSTEM_219_NATIVE_CODEX_SANDBOX_MITIGATION_RECORDED",
            "BLK_SYSTEM_218_THIRD_BOUNDED_KURONODE_FEATURE_LOOP_EXECUTED",
            "BLK_SYSTEM_217_CODEX_EXACT_UNDO_EXERCISE_RECORDED",
            "BLK_SYSTEM_216_CODEX_PERMISSION_PROFILE_CONTAINMENT_DRILL_RECORDED",
            "BLK_SYSTEM_215_SUPERVISED_CODEX_KURONODE_FEATURE_LOOP_EXECUTED",
            "BLK_SYSTEM_214_BOUNDED_KURONODE_FEATURE_LOOP_EXECUTED",
            "BLK_SYSTEM_213_BLK_TEST_OPTIONAL_DIAGNOSTIC_UNBLOCK_READY",
            "BLK_SYSTEM_212_VALIDATION_PROFILE_RECONCILED_CLEAN",
            "BLK_SYSTEM_211_VALIDATION_PROFILE_CONTRACT_READY",
            "BLK_SYSTEM_210_VALIDATION_PROFILE_SURFACE_REVIEW_READY",
            "BLK_SYSTEM_209_PYTHON_ADAPTER_RECONCILED_CLEAN",
            "BLK_SYSTEM_208_PYTHON_ADAPTER_CONTRACT_READY",
            "BLK_SYSTEM_207_PYTHON_ADAPTER_SURFACE_REVIEW_READY",
            "BLK_SYSTEM_206_BLK_PIPE_BOUNDED_ENFORCEMENT_RECONCILED_CLEAN",
            "BLK_SYSTEM_205_BLK_PIPE_BOUNDED_ENFORCEMENT_CONTRACT_READY",
            "BLK_SYSTEM_204_BLK_PIPE_SURFACE_REVIEW_READY",
            "BLK_SYSTEM_203_KURONODE_BLK_REQ_BRIDGE_RECONCILED_CLEAN",
            "BLK_SYSTEM_202_KURONODE_BLK_REQ_EXACT_ID_MAPPING_MATERIALIZED",
            "BLK_SYSTEM_201_KURONODE_BLK_REQ_EXACT_ID_MAPPING_MANIFEST_READY",
            "BLK_SYSTEM_200_KURONODE_BLK_REQ_VAULT_BOOTSTRAP_BLUEPRINT_READY",
            "BLK_SYSTEM_199_BLK_REQ_PRODUCTION_GATEWAY_RECONCILED_CLEAN",
            "BLK_SYSTEM_198_BLK_REQ_GATEWAY_HOSTILE_INPUTS_HARDENED",
            "BLK_SYSTEM_197_BLK_REQ_EXACT_ID_LIFECYCLE_SMOKE_PASSED",
            "BLK_SYSTEM_196_BLK_REQ_PRODUCTION_GATEWAY_CONTRACT_READY",
            "BLK_SYSTEM_195_BLK_REQ_GATEWAY_READINESS_REVIEW_CLEAN",
            "BLK_SYSTEM_194_REPEATABLE_TRUSTED_BLK_LINK_RECONCILED_CLEAN",
            "BLK_SYSTEM_193_REPEATABLE_TRUSTED_BLK_LINK_REPEAT_RUNS_RECORDED_CLEAN",
            "BLK_SYSTEM_192_REPEATABLE_TRUSTED_BLK_LINK_LEDGER_READY",
            "BLK_SYSTEM_191_REPEATABLE_TRUSTED_BLK_LINK_CONTRACT_EMITTED",
            "BLK_SYSTEM_190_REPEATABLE_TRUSTED_BLK_LINK_POST_RUN_REVIEW_CLEAN",
            "BLK_SYSTEM_189_SINGLE_PRODUCTION_BLK_LINK_WRAPPER_RUN_RECONCILED_CLEAN",
            "BLK_SYSTEM_188_SINGLE_PRODUCTION_BLK_LINK_WRAPPER_RUN_EXECUTION_RECORDED",
            "BLK_SYSTEM_187_SINGLE_PRODUCTION_BLK_LINK_WRAPPER_RUN_REQUEST_READY",
            "BLK_SYSTEM_186_REUSABLE_BLK_LINK_READINESS_KERNEL_RECONCILED_CLEAN",
            "BLK_SYSTEM_182_RTM_BLK_LINK_PROTECTED_BODY_EVIDENCE_EXPORT_RECONCILED_CLEAN",
            "BLK_SYSTEM_181_RTM_BLK_LINK_PROTECTED_BODY_EVIDENCE_METADATA_EXPORT_EMITTED",
            "BLK_SYSTEM_180_RTM_BLK_LINK_PROTECTED_BODY_EVIDENCE_FOLLOWUP_RECONCILED_CLEAN",
            "BLK_SYSTEM_179_RTM_BLK_LINK_PROTECTED_BODY_EVIDENCE_FOLLOWUP_EXECUTION_RECORDED",
            "BLK_SYSTEM_178_RTM_BLK_LINK_PROTECTED_BODY_EVIDENCE_FOLLOWUP_AUTHORITY_REQUEST_READY",
            "BLK_SYSTEM_177_AUTHORITY_LAUNDERING_BYPASS_HARDENED",
            "BLK_SYSTEM_176_RTM_BLK_LINK_PROTECTED_BODY_VERIFICATION_EVIDENCE_INTEGRATED",
            "BLK_SYSTEM_175_PROTECTED_BODY_VERIFICATION_DECISION_EXECUTION_RECORDED",
            "BLK_SYSTEM_174_PROTECTED_BODY_VERIFICATION_DECISION_AUTHORITY_REQUEST_READY",
            "BLK_SYSTEM_173_METADATA_BOUND_DRIFT_COVERAGE_DECISION_RECONCILED_CLEAN",
            "BLK_SYSTEM_172_METADATA_BOUND_DRIFT_COVERAGE_DECISION_EXECUTION_RECORDED",
            "BLK_SYSTEM_170_ACTIVE_VAULT_HASH_COMPARISON_RECONCILED_CLEAN",
            "BLK_SYSTEM_169_ACTIVE_VAULT_HASH_COMPARISON_DECISION_EXECUTION_RECORDED",
            "BLK_SYSTEM_168_ACTIVE_VAULT_HASH_COMPARISON_AUTHORITY_REQUEST_READY",
            "BLK_SYSTEM_167_PRODUCTION_BLK_LINK_RTM_TRACE_CLOSURE_POST_RUN_RECONCILED_CLEAN",
            "BLK_SYSTEM_166_PRODUCTION_BLK_LINK_RTM_TRACE_CLOSURE_DECISION_EXECUTION_RECORDED",
            "BLK_SYSTEM_165_PRODUCTION_BLK_LINK_RTM_TRACE_CLOSURE_AUTHORITY_REQUEST_READY",
            "BLK_SYSTEM_164_ACTIVE_DOC_DENIED_SURFACE_SYNC_HARDENED",
            "BLK_SYSTEM_163_CURRENT_STATE_DENIED_SURFACE_HARDENED",
        ]
        missing = [marker for marker in required if marker not in text]
        self.assertEqual(missing, [])
        self.assertLessEqual(len(text.splitlines()), 185)
        for marker in [
            "Root-Doctrine Gap Coverage and Proposed Sequence",
            "HITL identity/relay wiring lane",
            "Convenience/product lane",
            "Immediate real dependency",
            "full reusable BLK-003 autonomous loop",
            "production BLK-test MCP",
            "reusable BEO publication",
            "reusable RTM / production `blk-link`",
        ]:
            self.assertIn(marker, text)
        self.assertNotIn("or exact text for the refreshed challenge", text)
        self.assertNotIn("bounded `Approve` or exact text for the refreshed challenge", text)
        self.assertNotIn("NEXT_FRONTIER_EXACT_VERIFIED_LOOP_BEO_PUBLICATION_REFRESHED_BOUND_APPROVE_REQUIRED_NOT_GRANTED", text)
        self.assertNotIn("2026-05-21T20:45:00+10:00", text)
        self.assertNotIn("consume at most one run ID", text)
        self.assertNotIn("standing approval record, one run ID", text)
        self.assertNotIn("Capture BLK-SYSTEM-316 and execute", text)
        self.assertNotIn("publication finality package", text)
        self.assertNotIn("task-000", text.lower())
        self.assertNotIn("task-001", text.lower())

    def test_root_docs_are_fixed_overview_not_sprint_state_surfaces(self):
        forbidden = ["BLK-SYSTEM-", "BLK-PIPE-008", "Current-State Overlay", "current-state overlay"]
        for path in ROOT_DOCS:
            text = path.read_text()
            self.assertIn("BLK_001_TO_006_FIXED_OVERVIEW_NOT_SPRINT_STATE", text, path.name)
            self.assertIn("stable overview/contract surface", text, path.name)
            leaks = [marker for marker in forbidden if marker in text]
            self.assertEqual(leaks, [], path.name)

    def test_current_state_index_knows_lean_policy_without_becoming_sprint_plan(self):
        text = BLK079.read_text()
        for marker in [
            "LEAN_DOCUMENTATION_MODEL_ACTIVE",
            "NO_BLK_DOC_PER_SPRINT",
            "ONE_OUTCOME_PER_SPRINT_NO_TASK_OUTCOME_DOCS",
            "BLK_001_TO_006_FIXED_OVERVIEW_NOT_SPRINT_STATE",
        ]:
            self.assertIn(marker, text)
        self.assertIn("This document is not a sprint plan", text)

    def test_current_state_block_has_no_duplicate_blk_system_markers(self):
        text = BLK079.read_text()
        marker_block = re.search(r"## 2\. Current State\n```text\n(.*?)\n```", text, re.DOTALL)
        self.assertIsNotNone(marker_block)
        if marker_block is None:
            self.fail("current-state marker block missing")
        markers = re.findall(r"BLK_SYSTEM_\d+_[A-Z0-9_]+", marker_block.group(1))
        duplicates = sorted({marker for marker in markers if markers.count(marker) > 1})
        self.assertEqual(duplicates, [])

    def test_new_sprints_use_one_outcome_only(self):
        for sprint in range(121, 335):
            task_outcomes = list((DOCS / "outcomes").glob(f"BLK-SYSTEM-{sprint}_task-*-outcome.md"))
            self.assertEqual(task_outcomes, [], f"BLK-SYSTEM-{sprint} has per-task outcomes")
        for sprint in range(122, 335):
            allowed_durable_contracts = {
                "BLK-122_blk-id-blk-relay-provenance-contract.md",
                "BLK-123_speculative-quarantine-approval-contract.md",
                "BLK-124_reusable-blk003-loop-request-path-contract.md",
                "BLK-125_exact-quarantine-gated-blk003-loop-execution-contract.md",
                "BLK-126_exact-blk-test-oracle-verification-after-loop-contract.md",
                "BLK-127_verified-loop-beo-publication-review-contract.md",
                "BLK-128_verified-loop-beo-publication-approval-request-contract.md",
            }
            blk_docs = [
                path for path in DOCS.glob(f"BLK-{sprint}_*.md")
                if path.name not in allowed_durable_contracts
            ]
            self.assertEqual(blk_docs, [], f"BLK-{sprint} sprint doc should not exist")
            closeout = DOCS / "outcomes" / f"BLK-SYSTEM-{sprint}_sprint-closeout.md"
            self.assertTrue(closeout.exists(), f"BLK-SYSTEM-{sprint} closeout missing")
    def test_current_closeouts_do_not_keep_pending_verification_or_review_placeholders(self):
        for sprint in range(172, 335):
            path = DOCS / "outcomes" / f"BLK-SYSTEM-{sprint}_sprint-closeout.md"
            text = path.read_text()
            lowered = text.casefold()
            for stale in [
                "pending final rerun",
                "will be patched",
                "will be rerun",
                "final hostile review pending",
                "hostile review is pending",
                "independent hostile review is pending",
                "pending final closeout verification",
                "recorded after the closeout is finalized",
                "preliminary review conclusion",
                "part of final",
                "final independent hostile review",
                "commit closeout",
                "after the full closeout pass",
                "final package verification section",
            ]:
                self.assertNotIn(stale, lowered, path.name)


if __name__ == "__main__":
    unittest.main()
